version: "2"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    env_file: .env
  python:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/python-app
    ports:
      - "${HOST_IP}:1022:22"
      - "${HOST_IP}:80:8000"
