# Generated by Django 2.0.4 on 2018-04-08 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='advertisement',
            field=models.OneToOneField(on_delete='CASCADE', related_name='ad_statisic', to='dashboard.Advertisement'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
